name: flutter_twitter
description: A Flutter plugin for allowing users to authenticate with native Android &amp; iOS Twitter login SDKs.
version: 1.1.4
homepage: https://github.com/niubit-dev/flutter_twitter

dependencies:
  flutter_twitter_web:
    git:
      url: https://github.com/niubit-dev/flutter_twitter_web.git
      ref: master

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.roughike.fluttertwitterlogin.fluttertwitterlogin
        pluginClass: TwitterLoginPlugin
      ios:
        pluginClass: TwitterLoginPlugin
      web:
        default_package: flutter_twitter_web

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"